/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avk;

import com.pi4j.io.serial.Baud;
import com.pi4j.io.serial.DataBits;
import com.pi4j.io.serial.FlowControl;
import com.pi4j.io.serial.Parity;
import com.pi4j.io.serial.Serial;
import com.pi4j.io.serial.SerialConfig;
import com.pi4j.io.serial.SerialDataEvent;
import com.pi4j.io.serial.SerialDataEventListener;
import com.pi4j.io.serial.SerialFactory;
import com.pi4j.io.serial.SerialPort;
import com.pi4j.io.serial.StopBits;
import com.pi4j.util.Console;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TimerTask;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author murat
 */
public class Main extends javax.swing.JFrame {

 
    //Tam ekran kullanım değişkeni
    static GraphicsDevice device = GraphicsEnvironment
        .getLocalGraphicsEnvironment().getScreenDevices()[0];
    
    
    //Seri iletişim değişkenleri
    final Console console = new Console();
    final Serial serial = SerialFactory.createInstance();
    
    //Ekrana yazma işini sıraya koyma işini üstlenen thread düzenleyici
    ExecutorService service = Executors.newFixedThreadPool(3);
    
    //Gelen sıra numaralarını barındıran liste
    List<String> siraListesi = new ArrayList<>();
    
    ScheduledExecutorService executor =  Executors.newSingleThreadScheduledExecutor();

    public Main() {
        initComponents();
        device.setFullScreenWindow(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        seriIletisimProtokoluOlustur();
        executor.scheduleAtFixedRate(periodicTask, 1, 1, TimeUnit.SECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sira1 = new javax.swing.JTextField();
        sira1No = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        sira2 = new javax.swing.JTextField();
        sira2No = new javax.swing.JTextField();
        sira3 = new javax.swing.JTextField();
        sira3No = new javax.swing.JTextField();
        sira4 = new javax.swing.JTextField();
        sira4No = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        sira5 = new javax.swing.JTextField();
        sira5No = new javax.swing.JTextField();
        sonSiraBlinkText = new javax.swing.JLabel();
        sonSiraKabinBlinkText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(750, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/avk/resimler/logo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        sira1.setEditable(false);
        sira1.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira1.setText("  1  ");

        sira1No.setEditable(false);
        sira1No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira1No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira1No.setText("100");

        sira2.setEditable(false);
        sira2.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira2.setText("  2  ");

        sira2No.setEditable(false);
        sira2No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira2No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira2No.setText("100");

        sira3.setEditable(false);
        sira3.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira3.setText("  3  ");

        sira3No.setEditable(false);
        sira3No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira3No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira3No.setText("100");

        sira4.setEditable(false);
        sira4.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira4.setText("  4  ");

        sira4No.setEditable(false);
        sira4No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira4No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira4No.setText("100");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Kabin");
        jTextField3.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText(" Sıra ");
        jTextField4.setToolTipText("");
        jTextField4.setBorder(null);

        sira5.setEditable(false);
        sira5.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira5.setText("  5  ");

        sira5No.setEditable(false);
        sira5No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira5No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira5No.setText("100");

        sonSiraBlinkText.setFont(new java.awt.Font("Tahoma", 1, 63)); // NOI18N
        sonSiraBlinkText.setText("100");

        sonSiraKabinBlinkText.setFont(new java.awt.Font("Tahoma", 1, 41)); // NOI18N
        sonSiraKabinBlinkText.setText("Kabin 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sira4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira4No))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sira1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira1No))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira2No))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira3No))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira5No))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sonSiraBlinkText)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(sonSiraKabinBlinkText)
                                .addGap(77, 77, 77)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(sonSiraBlinkText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sonSiraKabinBlinkText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sira1No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sira2No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sira3No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sira4No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sira5No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField sira1;
    private javax.swing.JTextField sira1No;
    private javax.swing.JTextField sira2;
    private javax.swing.JTextField sira2No;
    private javax.swing.JTextField sira3;
    private javax.swing.JTextField sira3No;
    private javax.swing.JTextField sira4;
    private javax.swing.JTextField sira4No;
    private javax.swing.JTextField sira5;
    private javax.swing.JTextField sira5No;
    private javax.swing.JLabel sonSiraBlinkText;
    private javax.swing.JLabel sonSiraKabinBlinkText;
    // End of variables declaration//GEN-END:variables

    
    private void seriIletisimProtokoluOlustur() {
         // create and register the serial data listener
        serial.addListener((SerialDataEventListener) (SerialDataEvent event) -> {
            // NOTE! - It is extremely important to read the data received from the
            // serial port.  If it does not get read from the receive buffer, the
            // buffer will continue to grow and consume memory.
            
            // print out the data received to the console
            try {
                String gelenBilgi = event.getAsciiString();
                
                console.println("[HEX DATA]   " + event.getHexByteString());
                console.println("[ASCII DATA] " + gelenBilgi);
                
                if(gelenBilgi != null){
                    boolean parityKontrol = parityKontrolYap(gelenBilgi);
                    
                    if(parityKontrol){
                        
                        siraListesi.add(0, gelenBilgi);
                        
                        // now submit our jobs
                        service.submit(() -> {
                            ekraniGuncelle();
                        });
                    }
                }
                
                
            } catch (IOException e) {
                e.printStackTrace();
            }
        });
        
        
        try{
            // create serial config object
            SerialConfig config = new SerialConfig();
            
             // set default serial settings (device, baud rate, flow control, etc)
            //
            // by default, use the DEFAULT com port on the Raspberry Pi (exposed on GPIO header)
            // NOTE: this utility method will determine the default serial port for the
            //       detected platform and board/model.  For all Raspberry Pi models
            //       except the 3B, it will return "/dev/ttyAMA0".  For Raspberry Pi
            //       model 3B may return "/dev/ttyS0" or "/dev/ttyAMA0" depending on
            //       environment configuration.
            config.device(SerialPort.getDefaultPort())
               .baud(Baud._1200)
               .dataBits(DataBits._8)
               .parity(Parity.NONE)
               .stopBits(StopBits._1)
               .flowControl(FlowControl.NONE);

            // open the default serial device/port with the configuration settings
            serial.open(config);
        }catch(Exception e){
                
        }
    }
    
    
    
     private void ekraniGuncelle() {
         //son gelen sıra numarasını ekranda göster
         sonSiraBlinkText.setText(siraListesi.get(0));
         
         try{
             sira1No.setText(siraListesi.get(0));
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira2No.setText(siraListesi.get(1));
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira3No.setText(siraListesi.get(2));
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
        
         try{
            sira4No.setText(siraListesi.get(3));
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira5No.setText(siraListesi.get(4));
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
            
        
         if(siraListesi.size()>50)
            for(int i=5;i<siraListesi.size();i++){
                siraListesi.remove(i);
            }
                     
     }

    private boolean parityKontrolYap(String gelenBilgi) {
        return true;
    }

    int a = 0;
    private void sonSiraNumarasiBlink() {
       
        if(++a%2 == 0){
             sonSiraBlinkText.setForeground(Color.RED);
             sonSiraKabinBlinkText.setForeground(Color.RED);
        }else{
             sonSiraBlinkText.setForeground(Color.BLACK);
             sonSiraKabinBlinkText.setForeground(Color.BLACK);
        }
       
    }

   Runnable periodicTask = new Runnable() {
    public void run() {
        // Invoke method(s) to do the work
        sonSiraNumarasiBlink();
    }
};

    
}
