/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.avk;

import com.pi4j.io.serial.Baud;
import com.pi4j.io.serial.DataBits;
import com.pi4j.io.serial.FlowControl;
import com.pi4j.io.serial.Parity;
import com.pi4j.io.serial.Serial;
import com.pi4j.io.serial.SerialConfig;
import com.pi4j.io.serial.SerialDataEvent;
import com.pi4j.io.serial.SerialDataEventListener;
import com.pi4j.io.serial.SerialFactory;
import com.pi4j.io.serial.StopBits;
import com.pi4j.util.Console;
import java.awt.AWTKeyStroke;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineEvent;
import javax.swing.JFrame;

/**
 *
 * @author murat
 */
public class Main extends javax.swing.JFrame {

 
    //Tam ekran kullanım değişkeni
    static GraphicsDevice device = GraphicsEnvironment
        .getLocalGraphicsEnvironment().getScreenDevices()[0];
    
    
    
    //Seri iletişim değişkenleri
    final Console console = new Console();
    final Serial serial = SerialFactory.createInstance();
    
    //Ekrana yazma işini sıraya koyma işini üstlenen thread düzenleyici
    ExecutorService service = Executors.newFixedThreadPool(5);
    
    //Gelen sıra numaralarını barındıran liste
    List<String> siraListesi = new ArrayList<>();
    List<Sira> siraListesi2 = new ArrayList<>();
    
    ScheduledExecutorService executor =  Executors.newSingleThreadScheduledExecutor();

    public Main() {
        initComponents();
        device.setFullScreenWindow(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        seriIletisimProtokoluOlustur();
        executor.scheduleAtFixedRate(periodicTask, 1, 1, TimeUnit.SECONDS);
      
       this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sira1 = new javax.swing.JTextField();
        sira1No = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        sira2 = new javax.swing.JTextField();
        sira2No = new javax.swing.JTextField();
        sira3 = new javax.swing.JTextField();
        sira3No = new javax.swing.JTextField();
        sira4 = new javax.swing.JTextField();
        sira4No = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        sira5 = new javax.swing.JTextField();
        sira5No = new javax.swing.JTextField();
        sonSiraBlinkText = new javax.swing.JLabel();
        saat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(750, 600));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/avk/resimler/logo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        sira1.setEditable(false);
        sira1.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira1.setText("  1  ");

        sira1No.setEditable(false);
        sira1No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira1No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira1No.setText("100");

        sira2.setEditable(false);
        sira2.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira2.setText("  2  ");

        sira2No.setEditable(false);
        sira2No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira2No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira2No.setText("100");

        sira3.setEditable(false);
        sira3.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira3.setText("  3  ");

        sira3No.setEditable(false);
        sira3No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira3No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira3No.setText("100");

        sira4.setEditable(false);
        sira4.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira4.setText("  4  ");

        sira4No.setEditable(false);
        sira4No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira4No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira4No.setText("100");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Kabin");
        jTextField3.setBorder(null);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText(" Sıra ");
        jTextField4.setToolTipText("");
        jTextField4.setBorder(null);

        sira5.setEditable(false);
        sira5.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira5.setText("  5  ");
        sira5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sira5ActionPerformed(evt);
            }
        });

        sira5No.setEditable(false);
        sira5No.setFont(new java.awt.Font("Tahoma", 0, 43)); // NOI18N
        sira5No.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sira5No.setText("100");

        sonSiraBlinkText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 199)); // NOI18N
        sonSiraBlinkText.setText("100");

        saat.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        saat.setForeground(new java.awt.Color(102, 102, 255));
        saat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saat.setText("13:14");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZENİTTEK AR-GE LTD. ŞTİ");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sira4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira4No))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sira1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira1No))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira2No))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira3No))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sira5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sira5No))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(saat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sonSiraBlinkText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(sonSiraBlinkText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira1)
                    .addComponent(sira1No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira2)
                    .addComponent(sira2No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira3)
                    .addComponent(sira3No))
                .addGap(18, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira4)
                    .addComponent(sira4No))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sira5)
                    .addComponent(sira5No))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());
        AWTKeyStroke ak = AWTKeyStroke.getAWTKeyStrokeForEvent(evt);
        if(ak.equals(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_F4,evt.ALT_MASK)))
        {
          System.exit(0);
        }
     
    }//GEN-LAST:event_formKeyPressed

    private void sira5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sira5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sira5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel saat;
    private javax.swing.JTextField sira1;
    private javax.swing.JTextField sira1No;
    private javax.swing.JTextField sira2;
    private javax.swing.JTextField sira2No;
    private javax.swing.JTextField sira3;
    private javax.swing.JTextField sira3No;
    private javax.swing.JTextField sira4;
    private javax.swing.JTextField sira4No;
    private javax.swing.JTextField sira5;
    private javax.swing.JTextField sira5No;
    private javax.swing.JLabel sonSiraBlinkText;
    // End of variables declaration//GEN-END:variables

    
    private void seriIletisimProtokoluOlustur() {
        console.println("seri iletişi protokolü çalıştı");
         // create and register the serial data listener
        serial.addListener((SerialDataEventListener) (SerialDataEvent event) -> {
            // NOTE! - It is extremely important to read the data received from the
            // serial port.  If it does not get read from the receive buffer, the
            // buffer will continue to grow and consume memory.
            
            // print out the data received to the console
            try {
                //String gelenBilgi = event.getAsciiString();
                byte[] receivedBytes = event.getBytes();
                
                int[] sonBilgi = gelenBilgiKontrol(receivedBytes);
                //console.println("[HEX DATA]   " + event.getHexByteString());
                //console.println("[ASCII DATA] " + gelenBilgi);
                //System.out.println("gelen data : "+receivedBytes[0]+"  "+receivedBytes[1]+"  " +receivedBytes[2]);
             //   System.out.println(String.format("gelen bilgi : %d %s %s %s %s ",receivedBytes.length, receivedBytes[0],receivedBytes[1],receivedBytes[2],receivedBytes[3]));
                 System.out.println(String.format("gelen bilgi : %d %d %d %d %d ",sonBilgi.length, sonBilgi[0],sonBilgi[1],sonBilgi[2],sonBilgi[3]));
                if(crcKontrolYap(sonBilgi)){
                     gelenBilgiyiAnalizEt(sonBilgi);
                }
               
                /*
                if(gelenBilgi != null){
                    boolean parityKontrol = parityKontrolYap(gelenBilgi);
                    
                    if(parityKontrol){
                        
                        
                    }
                }
                */
                
            } catch (Exception e) {
                System.out.println("hata : "+e.getMessage());
            }
        });
        
        
        try{
            // create serial config object
            SerialConfig config = new SerialConfig();
            
             // set default serial settings (device, baud rate, flow control, etc)
            //
            // by default, use the DEFAULT com port on the Raspberry Pi (exposed on GPIO header)
            // NOTE: this utility method will determine the default serial port for the
            //       detected platform and board/model.  For all Raspberry Pi models
            //       except the 3B, it will return "/dev/ttyAMA0".  For Raspberry Pi
            //       model 3B may return "/dev/ttyS0" or "/dev/ttyAMA0" depending on
            //       environment configuration.
            config.device("/dev/ttyS0")
               .baud(Baud._1200)
               .dataBits(DataBits._8)
               .parity(Parity.NONE)
               .stopBits(StopBits._1)
               .flowControl(FlowControl.NONE);

            // open the default serial device/port with the configuration settings
            serial.open(config);
        }catch(Exception e){
          console.println("hata : " + e.getMessage());        
        }
    }
    
   
    
    
     private void ekraniGuncelle() {
         //son gelen sıra numarasını ekranda göster
         sonSiraBlinkText.setText(siraListesi2.get(0).getSiraNo());
         playSound2();
    
         
         
         try{
             sira1No.setText(siraListesi2.get(0).getSiraNo());
             sira1.setText(siraListesi2.get(0).getKabinNo());
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira2No.setText(siraListesi2.get(1).getSiraNo());
            sira2.setText(siraListesi2.get(1).getKabinNo());
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira3No.setText(siraListesi2.get(2).getSiraNo());
            sira3.setText(siraListesi2.get(2).getKabinNo());
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
        
         try{
            sira4No.setText(siraListesi2.get(3).getSiraNo());
            sira4.setText(siraListesi2.get(3).getKabinNo());
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
         
         try{
            sira5No.setText(siraListesi2.get(4).getSiraNo());
            sira5.setText(siraListesi2.get(4).getKabinNo());
         }catch(Exception e){
             System.out.println(e.getMessage());
         }
            
        
         if(siraListesi2.size()>50)
            for(int i=5;i<siraListesi2.size();i++){
                siraListesi2.remove(i);
            }        
     }
     
     
     
     

 
    
    
    
    int a = 0;
    int loopCounter = 0;
    private void sonSiraNumarasiBlink() {
 
        loopCounter++;

        if(++a%2 == 0){
            if(loopCounter<12) jTextFieldBlink(true); else jTextFieldBlink(false);
            sonSiraBlinkText.setForeground(Color.RED);
        }else{
            sonSiraBlinkText.setForeground(Color.BLACK);
            if(loopCounter<12) jTextFieldBlink(false); else jTextFieldBlink(false);
        }   
    }
    
    
    private void jTextFieldBlink(boolean durum){
        if(durum){
            sira1.setForeground(Color.WHITE);
             sira1No.setForeground(Color.WHITE);
             sira1.setBackground(Color.RED);
             sira1No.setBackground(Color.RED);
        }else{
             sira1.setForeground(Color.BLACK);
             sira1.setBackground(Color.WHITE);
             sira1No.setBackground(Color.WHITE);
             sira1No.setForeground(Color.BLACK);
        }
    }
    
    

   Runnable periodicTask = new Runnable() {
    public void run() {
        sonSiraNumarasiBlink();
    }
};
   
   
   
   AudioInputStream audioIn;
    Clip clip;
  private void sesAyarlari(){
      
      try{
           audioIn = AudioSystem.getAudioInputStream(new File("/home/pi/Music/uyari.wav"));
         
            clip = AudioSystem.getClip();
             clip.addLineListener(event -> {
               if(LineEvent.Type.STOP.equals(event.getType())) {
                   clip.close();
                   System.out.println("close");
               }
           });
           
      }catch(Exception ee){
          System.out.println(" hata : "+ee.getMessage());
      }
           
  }
   
 
  
  
  private void playSound2(){
      loopCounter = 0;
       try
        {
            AudioInputStream in = AudioSystem.getAudioInputStream(new File("/home/pi/Music/uyari.wav"));
            Line.Info linfo = new Line.Info(Clip.class);
            Line line = AudioSystem.getLine(linfo);
            Clip clip = (Clip) line;
           clip.addLineListener(event -> {
               if(LineEvent.Type.STOP.equals(event.getType())) {
                   clip.close();
                   System.out.println("close");
               }
           });
           
            //Clip clip = AudioSystem.getClip();
            clip.open(in);
            clip.start();
            long startTime = System.currentTimeMillis();

            int repeatDuration = 10;
            boolean playOnce = false;

            do
            {
                //Checks every 50 ms whether clip has completed or not. Only continues after completion
                Thread.sleep(50);
            }
            //Repeat while running and while clip time has not exceeded repeat duration
            while (clip.isRunning() && (System.currentTimeMillis() - startTime < repeatDuration * 1000 || playOnce));

            clip.stop();   //Stop if still running past max time
        } catch (Exception e) {
            e.printStackTrace();
        } 
    
  }

    private boolean crcKontrolYap(int[] receivedBytes) {
 
       boolean durum = false;
       try{
           /*
            int crc = Integer.parseInt( ""+receivedBytes[3] );
            int hi =  Integer.parseInt( ""+receivedBytes[2] );
            int lo =  Integer.parseInt( ""+receivedBytes[1]);
            int id =  Integer.parseInt( ""+receivedBytes[0] );  
          */
             int crc = receivedBytes[3] ;
            int hi =  receivedBytes[2] ;
            int lo =  receivedBytes[1];
            int id =  receivedBytes[0] ;  
            if (id+lo+hi == crc)
                durum = true;
       }catch(Exception e){
           System.out.println("hata : "+e.getMessage());
           
       }
       
       return true;
    }

    private void gelenBilgiyiAnalizEt(int[] receivedBytes) {
        try{
            int hi = receivedBytes[2] ;
            int lo = receivedBytes[1];
            int id =  receivedBytes[0] ;  
            
            switch(id){
                case 20:
                    saatDegistir(lo,hi);
                    break;
                case 50:
                    siraNumarasiGuncelle(lo,hi,1);
                    break;
                case 51:
                    siraNumarasiGuncelle(lo,hi,2);
                    break;
                case 52:
                    siraNumarasiGuncelle(lo,hi,3);
                    break;
                case 53:
                    siraNumarasiGuncelle(lo,hi,4);
                    break;    
                 
            }
                
       }catch(Exception e){
           System.out.println("hata : "+e.getMessage());
           
       }
    }

    private void saatDegistir(int s, int d) {
        String d_ = (d < 10 ? "0" : "") + d;
        String s_ = (s < 10 ? "0" : "") + s;
        saat.setText(String.format("%s:%s",s_,d_));
    }

    private void siraNumarasiGuncelle(int lo, int hi,int kabinNo) {
        
        int bilgi = hi * 256 + lo;
        
        Sira sira = new Sira(bilgi+"", kabinNo+"");
        
        siraListesi2.add(0, sira);
                        
        // now submit our jobs
        service.submit(() -> {
            ekraniGuncelle();
        });
    }

private int[] gelenBilgiKontrol(byte[] receivedBytes) {
        int[] son= new int[5];
        for (int i=0;i<receivedBytes.length;i++) {
            if( receivedBytes[i]>=0){
               son[i] = receivedBytes[i]; 
                System.out.println("büyük");
            }
            else{
                System.out.println("küçük");
                  son[i] =  (receivedBytes[i]+256);
            }
               
        }
        
        return son;
         
    }
    
}
